workflows:
  ios-release:

    triggering:
      events:
        - push

      branch_patterns:
        - pattern: main
          include: true
          source: true

    environment:
      flutter: stable
      xcode: latest

    integrations:
      app_store_connect: Apple Developer

    scripts:
      - flutter clean
      - flutter pub get

      - |
        cd ios
        pod install
        cd ..

      - flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration

        submit_to_testflight: true
        submit_to_app_store: false