name: cocbasepro
description: Coc Base Pro App
publish_to: "none"

version: 1.0.0+21

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^4.8.0
  connectivity_plus: ^6.0.5

  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.0

  url_launcher: ^6.3.2
  google_mobile_ads: ^5.1.0
  in_app_review: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/icon_ios.png


# =========================
# SPLASH SCREEN (CHỈ MÀU - KHÔNG LOGO)
# =========================
flutter_native_splash:
  color: "#1E88F0"
  fullscreen: true

  android: true
  ios: true

  android_12:
    color: "#1E88F0"


# =========================
# APP ICON
# =========================
flutter_launcher_icons:
  android: true
  ios: true

  image_path_android: "assets/icon.png"

  adaptive_icon_background: "#1E88F0"
  adaptive_icon_foreground: "assets/icon.png"

  image_path_ios: "assets/icon_ios.png"

  remove_alpha_ios: true