name: cocbasepro
description: Coc Base Pro App
publish_to: "none"

version: 5.6.0+21




environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: 4.7.0
  webview_flutter_wkwebview: 3.13.1
  connectivity_plus: ^6.0.5

  url_launcher: ^6.3.2
  google_mobile_ads: ^5.1.0
  http: ^1.2.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png

flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/icon_ios.jpg"
  remove_alpha_ios: true

