// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQKrqSHOiy8ExUMCDH-unZ1s932TSdPbA',
    appId: '1:27868110886:web:788fea04b10e321fa006e7',
    messagingSenderId: '27868110886',
    projectId: 'cocbaseapp',
    authDomain: 'cocbaseapp.firebaseapp.com',
    storageBucket: 'cocbaseapp.firebasestorage.app',
    measurementId: 'G-Y9DXW74NZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAMEfA87PRcioPaPHNCYQfrLOHgAZhVnQ',
    appId: '1:27868110886:android:f7f6a85122057109a006e7',
    messagingSenderId: '27868110886',
    projectId: 'cocbaseapp',
    storageBucket: 'cocbaseapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFN28ruxvpgVVfyeAGbAgKu1t-7HotRcQ',
    appId: '1:27868110886:ios:3f3079b61ffad806a006e7',
    messagingSenderId: '27868110886',
    projectId: 'cocbaseapp',
    storageBucket: 'cocbaseapp.firebasestorage.app',
    iosBundleId: 'com.hoangvuong.cocbasepro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFN28ruxvpgVVfyeAGbAgKu1t-7HotRcQ',
    appId: '1:27868110886:ios:3b5f87264a86eaeca006e7',
    messagingSenderId: '27868110886',
    projectId: 'cocbaseapp',
    storageBucket: 'cocbaseapp.firebasestorage.app',
    iosBundleId: 'com.example.cocbasepro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQKrqSHOiy8ExUMCDH-unZ1s932TSdPbA',
    appId: '1:27868110886:web:aacca4ec1966238aa006e7',
    messagingSenderId: '27868110886',
    projectId: 'cocbaseapp',
    authDomain: 'cocbaseapp.firebaseapp.com',
    storageBucket: 'cocbaseapp.firebasestorage.app',
    measurementId: 'G-T3Q1QKPJHC',
  );
}
